In [1]:
from utils.config_helper import create_yaml
import os
dir = '/braintree/home/aliya277/inventory/'
array_meta_path  = '/braintree/data2/active/users/sgouldin/array-metadata'
for files in os.listdir(dir):
    num_files = 0
    path = os.path.join(dir, files)
    try: 
        num_files = len(os.listdir(os.path.join(path,'SpikeTimes')))
    except: pass

    if num_files == 192: 
        array_metadata = os.path.join(array_meta_path, '021023_pico_mapping_noCIT_adapter_version.json')
        adapter_info_avail = True
    elif num_files == 288: 
        array_metadata = os.path.join(array_meta_path,'pico_firstmapping_Lhem_2023.json')
        adapter_info_avail = False
        
        print(path)
    create_yaml(path, array_metadata, adapter_info_avail)

    # except: print(f'Check: {files}')

/braintree/home/aliya277/inventory/norm_FOSS.sub_pico.20220901_144739.proc
/braintree/home/aliya277/inventory/norm_FOSS.sub_pico.20220929_170635.proc
/braintree/home/aliya277/inventory/norm_FOSS.sub_pico.20220930_151743.proc
/braintree/home/aliya277/inventory/norm_FOSS.sub_pico.20220615_113442.proc
/braintree/home/aliya277/inventory/norm_FOSS.sub_pico.20220902_145351.proc
/braintree/home/aliya277/inventory/norm_FOSS.sub_pico.20220907_142157.proc
/braintree/home/aliya277/inventory/exp_ko_context_size.sub_pico.20220930_153358.proc
/braintree/home/aliya277/inventory/norm_FOSS.sub_pico.20220616_111545.proc
/braintree/home/aliya277/inventory/exp_MURI1320.sub_pico.20220615_115139.proc


In [10]:
import pandas as pd
df_ = pd.read_excel( '/braintree/home/aliya277/dandi_brainscore/pico_inventory.xlsx'  )
df_

ImageSet    date    time  Has SpikeTime  Has h5  Has Excel  \
0              normalizers  220627  142926              0       0          1   
1              normalizers  220616  111545              1       1          1   
2              normalizers  220622  150342              0       0          1   
3              normalizers  220623  153305              0       0          1   
4              normalizers  220624  144313              0       0          1   
..                     ...     ...     ...            ...     ...        ...   
423                    afv  230925  120343              1       1          0   
424      Kar_2023_degraded  230925  113603              1       1          0   
425  robustness_guy_d0_v40  230927  102628              1       0          0   
426  robustness_guy_d1_v41  230929  125427              1       0          0   
427  robustness_guy_d1_v41  230929  102605              1       0          0   

     (excel) Index (excel) Stimuli (excel) Num Reps  (excel) Num Images  \
0             75.0     Normalizers               15                86.0   
1             64.0     Normalizers               20                86.0   
2             68.0     Normalizers               17                86.0   
3             71.0     Normalizers               20                86.0   
4             73.0     Normalizers               20                86.0   
..             ...             ...              ...                 ...   
423            NaN             NaN              NaN                 NaN   
424            NaN             NaN              NaN                 NaN   
425            NaN             NaN              NaN                 NaN   
426            NaN             NaN              NaN                 NaN   
427            NaN             NaN              NaN                 NaN   

     (excel) Total Num Images  \
0                      1290.0   
1                      1720.0   
2                      1462.0   
3                      1720.0   
4                      1720.0   
..                        ...   
423                       NaN   
424                       NaN   
425                       NaN   
426                       NaN   
427                       NaN   

                                      Path: SpikeTimes  \
0                                                  NaN   
1    /braintree/data2/active/users/sgouldin/project...   
2                                                  NaN   
3                                                  NaN   
4                                                  NaN   
..                                                 ...   
423  /braintree/data2/active/users/sgouldin/project...   
424  /braintree/data2/active/users/sgouldin/project...   
425  /braintree/data2/active/users/sgouldin/project...   
426  /braintree/data2/active/users/sgouldin/project...   
427  /braintree/data2/active/users/sgouldin/project...   

                                              Path: h5  \
0                                                  NaN   
1    /braintree/data2/active/users/sgouldin/project...   
2                                                  NaN   
3                                                  NaN   
4                                                  NaN   
..                                                 ...   
423  /braintree/data2/active/users/sgouldin/project...   
424  /braintree/data2/active/users/sgouldin/project...   
425                                                NaN   
426                                                NaN   
427                                                NaN   

                                        Path: intanraw  
0    /braintree/data2/active/users/sgouldin/project...  
1    /braintree/data2/active/users/sgouldin/project...  
2    /braintree/data2/active/users/sgouldin/project...  
3    /braintree/data2/active/users/sgouldin/project...  
4    /braintree/data2/active/users/sgouldin/project...  
..                     

In [21]:
arr, count = np.unique(np.array(df_['ImageSet']), return_counts=True)
sum(count)

428

In [22]:
layer0=[]
layer1=[]
layer2=[]
layer3=[]
layer4=[]
layer5=[]
import numpy as np

for spike, h5 , excel, img in zip(df_['Has SpikeTime'], df_['Has h5'], df_['Has Excel'], df_['ImageSet']):
    if img == 'normalizers' or img == 'normalizers-HVM':
        layer0.append(0)
        if excel == 1:
            layer1.append(0)
        else:
            layer1.append(1)
        if spike == 1:
            layer2.append(0)
        else:
            layer2.append(1)
        if h5 == 1:
            layer3.append(0)
        else:
            layer3.append(1)

    else:
        layer0.append(1)
        if excel == 1:
            layer1.append(2)
        else:
            layer1.append(3)
        if spike == 1:
            layer2.append(2)
        else:
            layer2.append(3)
        if h5 == 1:
            layer3.append(2)
        else:
            layer3.append(3)

print('normalizers, rest')
print(np.unique(layer0, return_counts=True))
print('has excel, has not')
print(np.unique(layer1, return_counts=True))
print('has spike, has not')
print(np.unique(layer2, return_counts=True))
print('has h5, has not')
print(np.unique(layer3, return_counts=True))

normalizers, rest
(array([0, 1]), array([199, 229]))
has excel, has not
(array([0, 1, 2, 3]), array([191,   8, 215,  14]))
has spike, has not
(array([0, 1, 2, 3]), array([107,  92, 116, 113]))
has h5, has not
(array([0, 1, 2, 3]), array([ 92, 107,  33, 196]))


In [24]:
import plotly.express as px

# Define the data for the treemap
data = {
    'Category': ['All Recordings', 'Has Excel', 'Has SpikeTime', 'SpikeTime'],
    'Parent': ['', 'All Recordings', 'Has Excel', 'Has Excel'],
    'Value': [400, 300, 100, 100]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Create a treemap
fig = px.treemap(df, names='Category', parents='Parent', values='Value',color_discrete_sequence=px.colors.sequential.Viridis)


fig.update_traces(textinfo="label+text")

# Show the treemap
fig.show()

In [6]:
import plotly.express as px
# df = df_.drop([259:259])
df_plot = df_
df_plot['Has SpikeTime'].replace({0: 'No SpikeTime', 1:'SpikeTime'}, inplace=True)
df_plot['Has h5'].replace({0: 'No psth', 1:'psth'}, inplace=True)
df_plot['Has Excel'].replace({0: 'No excel', 1:'excel'}, inplace=True)
fig = px.sunburst(df_plot, path=['ImageSet', 'Has Excel', 'Has SpikeTime', 'Has h5'], values='date', width=1000, height=1000)
fig.show()
# df

In [34]:

import h5py
import os 
import numpy as np 

path = '/braintree/home/aliya277/inventory/exp_gratingsAdap_s5.sub_pico.20230801_144134.proc'
filename = '230801.pico.rsvp.gratingsAdap_s5.experiment_psth_raw.h5'
file = h5py.File(os.path.join(path, 'h5Files', filename),'r+') 
file.close()
# data = file['psth'][:]
# meta = np.array([np.array(file['meta']['start_time_ms']), np.array(file['meta']['stop_time_ms']), np.array(file['meta']['tb_ms'])])
# print(meta)

In [18]:
import io, os, pynwb
from pynwb import NWBHDF5IO
from nwbwidgets import nwb2widget
############### Check if All Files are Written and can be Opened ##############
###############################################################################

inventory   = '/braintree/home/aliya277/inventory/'
all_files = os.listdir(inventory)
for folder in all_files[:24]:
        path = os.path.join(inventory, folder)
        try:
                io = NWBHDF5IO(os.path.join(path, f"{folder}.nwb"), "r") 
                nwbfile = io.read()
                io.close()
        except: print(f'This File can not be opened: {folder}')


In [19]:
############### Validate All Files Using pwnyb, nwbinspectors #################
###############################################################################

import io, os, pynwb
from pynwb import validate
from nwbinspector import inspect_nwbfile

inventory   = '/braintree/home/aliya277/inventory/'
all_nwb_paths = []
all_files = os.listdir(inventory)
for folder in all_files[:24]:
    path = os.path.join(inventory, folder, f'{folder}.nwb')
    all_nwb_paths.append(path)
    


pynwb_validation = validate(paths = all_nwb_paths)

nwbinspector_validation = []
for path in all_nwb_paths:
    results = list(inspect_nwbfile(nwbfile_path=path))
    nwbinspector_validation.append(results)

In [29]:
from dandi import validate 

dandi = validate.validate(all_nwb_paths[0])
print(dandi)

<generator object validate at 0x7f69be3c3cd0>


In [20]:
nwbinspector_validation

[[],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 []]

In [21]:
pynwb_validation

([], 0)

In [11]:
import io, os, pynwb
from pynwb import NWBHDF5IO
from nwbwidgets import nwb2widget

inventory   = '/braintree/home/aliya277/inventory/'
all_files = os.listdir(inventory)
folder = all_files[0]
path = os.path.join(inventory, folder, f'{folder}.nwb')
io = NWBHDF5IO(path, "r") 
nwbfile = io.read()
# io.close()
nwb2widget(nwbfile)

In [14]:
nwbfile.subject.sex = 'M'

AttributeError: can't set attribute 'sex' -- already set

In [6]:
import io, os, pynwb
inventory   = '/braintree/home/aliya277/inventory/'
all_nwb_paths = []
all_files = os.listdir(inventory)
for folder in all_files:
    path = os.path.join(inventory, folder, f'{folder}.nwb')
    all_nwb_paths.append(path)
all_files

['exp_Alireza_paradigm1.sub_pico.20230616_103724.proc',
 'exp_domain_transfer_2023.sub_pico.20230216_150919.proc',
 'exp_domain_transfer_2023.sub_pico.20230223_134049.proc',
 'exp_facesMSFDE.sub_pico.20230327_134955.proc',
 'exp_gratingsAdap_s3.sub_pico.20230801_163355.proc',
 'exp_gratingsAdap_s5.sub_pico.20230801_144134.proc',
 'exp_HVM_var6.sub_pico.20230221_142542.proc',
 'exp_HVM_var6.sub_pico.20230223_150327.proc',
 'exp_HVM-var6-subset.sub_pico.20230303_180103.proc',
 'exp_images_in_context3.sub_pico.20230531_135649.proc',
 'exp_images_in_context.sub_pico.20230324_121431.proc',
 'exp_Mayo_day_1.sub_pico.20230814_124244.proc',
 'exp_Mayo_day_1.sub_pico.20230814_143555.proc',
 'exp_Mayo_day_2.sub_pico.20230815_111611.proc',
 'exp_Mayo_day_5.sub_pico.20230818_121533.proc',
 'exp_Mayo_ONR.sub_pico.20230804_154202.proc',
 'exp_Mayo_ONR.sub_pico.20230808_143723.proc',
 'exp_moca.sub_pico.20230719_123506.proc',
 'exp_MURI1320-2023.sub_pico.20230131_183129.proc',
 'exp_MURI1320-2023.sub

In [7]:
from pynwb import validate

validate(paths = all_nwb_paths[0:5])

([], 0)

In [17]:
from nwbinspector import inspect_nwbfile

for path in all_nwb_paths[0:10]:
    results = list(inspect_nwbfile(nwbfile_path=path))
    print(results)

[InspectorMessage(
    message='Description is missing.',
    importance=<Importance.BEST_PRACTICE_SUGGESTION: 0>,
    severity=<Severity.LOW: 1>,
    check_function_name='check_description',
    object_type='Subject',
    object_name='subject',
    location='/general/subject',
    file_path='/braintree/home/aliya277/inventory/exp_Alireza_paradigm1.sub_pico.20230616_103724.proc/exp_Alireza_paradigm1.sub_pico.20230616_103724.proc.nwb'
), InspectorMessage(
    message="Subject.sex should be one of: 'M' (male), 'F' (female), 'O' (other), or 'U' (unknown).",
    importance=<Importance.BEST_PRACTICE_SUGGESTION: 0>,
    severity=<Severity.LOW: 1>,
    check_function_name='check_subject_sex',
    object_type='Subject',
    object_name='subject',
    location='/general/subject',
    file_path='/braintree/home/aliya277/inventory/exp_Alireza_paradigm1.sub_pico.20230616_103724.proc/exp_Alireza_paradigm1.sub_pico.20230616_103724.proc.nwb'
)]
[InspectorMessage(
    message='Description is missing.'